options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # //? Step 1: Lint
  - name: 'node:20-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm i -g pnpm && pnpm install --frozen-lockfile
        pnpm run lint

  # //? Step 2: Testing
  - name: 'node:20-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm i -g pnpm && pnpm install && pnpm test

  # //? Step 3: Compilation
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/finance-api', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/finance-api']

  # //? Step 4: Deployment
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'finance-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/finance-api'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/finance-api'
