import { CreateTransactionDto } from '../transaction/dto/create-transaction.dto';
import { TransactionType } from '../transaction/entities/transaction.entity';
import { CreateUserDto } from '../auth/dto/create-user.dto';
import { Currency, PaymentInterval, PaymentPlanStatus } from './enums';
import { CreatePaymentPlanDto } from '../payment-plan/dto/create-payment-plan.dto';

export const seedUsers: CreateUserDto[] = [
  {
    id: '6c93a91a-624f-47c4-ba0c-4b54612a83f3',
    username: 'Daniel Román',
    email: 'danielroman.05111@gmail.com',
    picture:
      'https://lh3.googleusercontent.com/a/ACg8ocLGbSxbKYojuPEqO0fdNpuZ1ia8zywu3IFEFRFyt0yxhTez-0hA=s96-c',
  },
  {
    id: 'f30fb304-acde-4fe1-bab4-78a4849893a2',
    username: 'Daker R',
    email: 'daker.dev@gmail.com',
    picture:
      'https://lh3.googleusercontent.com/a/ACg8ocIKJpwecoomty3swLOJyhBp3pim-YVFw1T9EVXYZB-mIvwpZg=s96-c',
  },
  {
    id: '715c869d-a886-46aa-a546-af55329b648b',
    username: 'Daker 11',
    email: 'dakerpro93@gmail.com',
    picture:
      'https://lh3.googleusercontent.com/a/ACg8ocJdnYHFpua5VFJrTNDqlaEgdM2-tVpdJD69tdfxFu39SpeBU1BB=s96-c',
  },
];

export const seedTransactions: CreateTransactionDto[] = [
  {
    name: 'Salary Jan',
    amount: 3000,
    type: TransactionType.INCOME,
    description: 'Monthly salary payment',
    createdAt: '2025-05-01T08:00:00Z',
    category: {
      id: 1,
      name: 'Work',
    },
    userId: seedUsers[0].id,
  },
  {
    name: 'Freelance Project',
    amount: 800,
    type: TransactionType.INCOME,
    description: 'Payment for freelance web project',
    createdAt: '2025-05-15T10:00:00Z',
    category: { name: 'Freelance' },
    userId: seedUsers[1].id,
  },
  {
    name: 'Groceries',
    amount: 150,
    type: TransactionType.EXPENSE,
    description: 'Weekly groceries shopping',
    createdAt: '2025-05-05T16:00:00Z',
    category: { name: 'Food' },
    userId: seedUsers[2].id,
  },
  {
    name: 'Electricity Bill',
    amount: 100,
    type: TransactionType.EXPENSE,
    description: 'Monthly electricity bill',
    createdAt: '2025-05-07T09:00:00Z',
    category: { name: 'Utilities' },
    userId: seedUsers[0].id,
  },
  {
    name: 'Internet Bill',
    amount: 60,
    type: TransactionType.EXPENSE,
    description: 'Monthly internet subscription',
    createdAt: '2025-05-07T09:30:00Z',
    category: { name: 'Utilities' },
    userId: seedUsers[1].id,
  },
  {
    name: 'Gym Membership',
    amount: 40,
    type: TransactionType.EXPENSE,
    description: 'Monthly gym membership fee',
    createdAt: '2025-05-10T18:00:00Z',
    category: { name: 'Health' },
    userId: seedUsers[2].id,
  },
  {
    name: 'Dinner Out',
    amount: 70,
    type: TransactionType.EXPENSE,
    description: 'Dinner with friends',
    createdAt: '2025-05-12T20:00:00Z',
    category: { name: 'Entertainment' },
    userId: seedUsers[0].id,
  },
  {
    name: 'Stock Dividends',
    amount: 120,
    type: TransactionType.INCOME,
    description: 'Quarterly dividends received',
    createdAt: '2025-05-20T12:00:00Z',
    category: { name: 'Investments' },
    userId: seedUsers[1].id,
  },
  {
    name: 'Coffee at Starbucks',
    amount: 5,
    type: TransactionType.EXPENSE,
    description: 'Morning coffee',
    createdAt: '2025-05-18T08:30:00Z',
    category: { name: 'Food' },
    userId: seedUsers[2].id,
  },
  {
    name: 'Uber Ride',
    amount: 12,
    type: TransactionType.EXPENSE,
    description: 'Ride to work',
    createdAt: '2025-05-17T09:15:00Z',
    category: { name: 'Transport' },
    userId: seedUsers[0].id,
  },
  {
    name: 'Spotify Subscription',
    amount: 10,
    type: TransactionType.EXPENSE,
    description: 'Monthly music subscription',
    createdAt: '2025-05-16T14:00:00Z',
    category: { name: 'Entertainment' },
    userId: seedUsers[1].id,
  },
  {
    name: 'Sold Old Phone',
    amount: 150,
    type: TransactionType.INCOME,
    description: 'Selling used iPhone',
    createdAt: '2025-05-16T16:30:00Z',
    category: { name: 'Resale' },
    userId: seedUsers[2].id,
  },
  {
    name: 'Lunch with Colleague',
    amount: 25,
    type: TransactionType.EXPENSE,
    description: 'Work lunch at local café',
    createdAt: '2025-05-15T13:00:00Z',
    category: { name: 'Food' },
    userId: seedUsers[0].id,
  },
  {
    name: 'Online Course Sale',
    amount: 200,
    type: TransactionType.INCOME,
    description: 'Revenue from Udemy course',
    createdAt: '2025-05-15T10:45:00Z',
    category: { name: 'Freelance' },
    userId: seedUsers[1].id,
  },
];

export const transactionsWithExistingCategories: CreateTransactionDto[] = [
  {
    name: 'Salary',
    amount: 3000,
    type: TransactionType.INCOME,
    description: 'Monthly salary payment',
    createdAt: '2025-05-01T08:00:00Z',
    category: {
      name: 'Work',
    },
    userId: seedUsers[0].id,
  },
  {
    name: 'Freelance Project',
    amount: 800,
    type: TransactionType.INCOME,
    description: 'Payment for freelance web project',
    createdAt: '2025-05-15T10:00:00Z',
    category: {
      id: 2,
      name: 'Freelance',
    },
    userId: seedUsers[1].id,
  },
  {
    name: 'Groceries',
    amount: 150,
    type: TransactionType.EXPENSE,
    description: 'Weekly groceries shopping',
    createdAt: '2025-05-05T16:00:00Z',
    category: {
      id: 3,
      name: 'Food',
    },
    userId: seedUsers[0].id,
  },
  {
    name: 'Electricity Bill',
    amount: 100,
    type: TransactionType.EXPENSE,
    description: 'Monthly electricity bill',
    createdAt: '2025-05-07T09:00:00Z',
    category: {
      id: 4,
      name: 'Utilities',
    },
    userId: seedUsers[0].id,
  },
  {
    name: 'Internet Bill',
    amount: 60,
    type: TransactionType.EXPENSE,
    description: 'Monthly internet subscription',
    createdAt: '2025-05-07T09:30:00Z',
    category: {
      id: 4,
      name: 'Utilities',
    },
    userId: seedUsers[0].id,
  },
  {
    name: 'Gym Membership',
    amount: 40,
    type: TransactionType.EXPENSE,
    description: 'Monthly gym membership fee',
    createdAt: '2025-05-10T18:00:00Z',
    category: {
      id: 5,
      name: 'Health',
    },
    userId: seedUsers[0].id,
  },
  {
    name: 'Dinner Out',
    amount: 70,
    type: TransactionType.EXPENSE,
    description: 'Dinner with friends',
    createdAt: '2025-05-12T20:00:00Z',
    category: {
      id: 6,
      name: 'Entertainment',
    },
    userId: seedUsers[0].id,
  },
  {
    name: 'Stock Dividends',
    amount: 120,
    type: TransactionType.INCOME,
    description: 'Quarterly dividends received',
    createdAt: '2025-05-20T12:00:00Z',
    category: {
      id: 7,
      name: 'Investments',
    },
    userId: seedUsers[1].id,
  },
  {
    name: 'Coffee at Starbucks',
    amount: 5,
    type: TransactionType.EXPENSE,
    description: 'Morning coffee',
    createdAt: '2025-05-18T08:30:00Z',
    category: {
      id: 3,
      name: 'Food',
    },
    userId: seedUsers[2].id,
  },
  {
    name: 'Uber Ride',
    amount: 12,
    type: TransactionType.EXPENSE,
    description: 'Ride to work',
    createdAt: '2025-05-17T09:15:00Z',
    category: {
      id: 8,
      name: 'Transport',
    },
    userId: seedUsers[2].id,
  },
  {
    name: 'Spotify Subscription',
    amount: 10,
    type: TransactionType.EXPENSE,
    description: 'Monthly music subscription',
    createdAt: '2025-05-16T14:00:00Z',
    category: {
      id: 6,
      name: 'Entertainment',
    },
    userId: seedUsers[2].id,
  },
  {
    name: 'Sold Old Phone',
    amount: 150,
    type: TransactionType.INCOME,
    description: 'Selling used iPhone',
    createdAt: '2025-05-16T16:30:00Z',
    category: {
      id: 9,
      name: 'Resale',
    },
    userId: seedUsers[1].id,
  },
  {
    name: 'Lunch with Colleague',
    amount: 25,
    type: TransactionType.EXPENSE,
    description: 'Work lunch at local café',
    createdAt: '2025-05-15T13:00:00Z',
    category: {
      id: 3,
      name: 'Food',
    },
    userId: seedUsers[0].id,
  },
  {
    name: 'Online Course Sale',
    amount: 200,
    type: TransactionType.INCOME,
    description: 'Revenue from Udemy course',
    createdAt: '2025-05-15T10:45:00Z',
    category: {
      id: 2,
      name: 'Freelance',
    },
    userId: seedUsers[0].id,
  },
];

export const seedTransactionPlans: CreatePaymentPlanDto[] = [
  {
    ownerId: seedUsers[0].id,
    name: 'Viaje a España',
    totalAmount: 10000000,
    currency: Currency.COP,
    interval: PaymentInterval.WEEKLY,
    status: PaymentPlanStatus.ACTIVE,
    startDate: '2025-05-11',
    endDate: '2025-05-11',
    participantIds: [seedUsers[0].id, seedUsers[1].id],
  },
  {
    ownerId: seedUsers[0].id,
    name: 'Pagar carro',
    totalAmount: 10000000,
    currency: Currency.COP,
    interval: PaymentInterval.WEEKLY,
    status: PaymentPlanStatus.ACTIVE,
    startDate: '2025-05-11',
    endDate: '2025-05-11',
    participantIds: [seedUsers[0].id, seedUsers[2].id],
  },
];
